apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "loan-risk-engine.fullname" . }}-config
  labels:
    {{- include "loan-risk-engine.labels" . | nindent 4 }}
data:
  ENVIRONMENT: {{ .Values.env.ENVIRONMENT | quote }}
  KAFKA_BOOTSTRAP_SERVERS: {{ .Values.env.KAFKA_BOOTSTRAP_SERVERS | quote }}
  KAFKA_TOPIC_LOAN_APPLICATIONS: {{ .Values.env.KAFKA_TOPIC_LOAN_APPLICATIONS | quote }}
  WEIGHT_DTI: {{ .Values.env.WEIGHT_DTI | quote }}
  WEIGHT_LTV: {{ .Values.env.WEIGHT_LTV | quote }}
  WEIGHT_P_INSTANCES: {{ .Values.env.WEIGHT_P_INSTANCES | quote }}
  THRESHOLD_CRITICAL: {{ .Values.env.THRESHOLD_CRITICAL | quote }}
  THRESHOLD_WATCHLIST: {{ .Values.env.THRESHOLD_WATCHLIST | quote }}
