apiVersion: v1
kind: Secret
metadata:
  name: {{ include "loan-risk-engine.fullname" . }}-secrets
  labels:
    {{- include "loan-risk-engine.labels" . | nindent 4 }}
type: Opaque
stringData:
  DATABASE_URL: {{ .Values.secrets.databaseUrl | quote }}
